# Generated by Django 3.2.3 on 2024-10-13 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20241013_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(error_messages={'cooking_time': {'max_value': 'Время приготовления не должно превышать 32000 минут.', 'min_value': 'Время приготовления должно быть больше 0.'}}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name='Время приготовления (мин.)'),
        ),
    ]
